### ISSUE TITLE
Missing information about the website being repurposed.

### ISSUE THREAD

**Issue by alexandra-valkova** [mikeyhogarth/green-web-dev#49]
Hello, I stumbled upon this repo through your **The Green Web Dev Book** webpage that has seemingly replaced this current one, according to this message in the home page:

> This site is being repurposed into an e-book called [The Green Web Dev Book](https://mikeyhogarth.github.io/the-green-web-dev-book/) and will therefore receive no further updates. We will be shutting down some time in 2023.

Could you add in the description of this repository that the [website](greenwebdev.org) is no longer online and a link to your new [repo](https://github.com/mikeyhogarth/the-green-web-dev-book)? I had to run the source code to figure out that you've moved the information into a new format. You could also pin it on your profile page, instead of this one :octocat:

Thanks for writing this e-book and freely sharing it online 💚

**Comment by mikeyhogarth** [comment]
Thanks @alexandra-valkova
